on:
  push
name: Testing linkcheck
jobs:
  blc-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: blc
      id: link-report
      uses: ./
      with:
        url: 'https://github.com/ocular-d/blc-action'
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"