on:
  push
name: Testing linkcheck
jobs:
  blc-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: blc
      uses: ./
      with:
        url: 'https://github.com/ocular-d/blc-action'